[browser]
gatherUsageStats = false

[server]
port = 8501
maxUploadSize = 200

[theme]
primaryColor = "#1f4e79"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "info" 