# Streamlit secrets configuration for ML Helper App
# Replace the placeholder values below with your actual Snowflake credentials
# 
# To find your account identifier:
# 1. Go to https://app.snowflake.com
# 2. Look at the URL after logging in: https://app.snowflake.com/REGION/ACCOUNT/
# 3. Your account identifier is: ACCOUNT.REGION (e.g., "abc12345.us-east-1")
#
# For Snowflake trial accounts, the format is usually: XXXXXXXX.snowflakecomputing.com

[snowflake]
# Account identifier (from your SnowSQL config)
account = "sfsenorthamerica-demo_sreed"

# Your Snowflake username (from your SnowSQL config)
user = "sreed"

# Your Snowflake password (from your SnowSQL config)
password = "Baseball#7"

# Role from your SnowSQL config
role = "HOL_ROLE"

# Warehouse from your SnowSQL config  
warehouse = "HOL_WH"

# Database name (will be created by setup script)
database = "ML_HELPER_APP"

# Schema name (will be created by setup script)
schema = "CORE"

# Optional: Additional connection parameters
# Uncomment and configure if needed
# region = "us-east-1"
# authenticator = "snowflake"
# warehouse_size = "MEDIUM" 